#!/bin/bash

# Before deploy kill all local simulation
pm2 delete all

set -o nounset
set -o errexit
set -o pipefail

rm -rf data*
rm -rf isolate*

# put last git commit into readable file
git rev-parse HEAD > HEAD
#--exclude 'dist'
rsync . root@188.120.244.199:~/f -rv  --exclude '.git' --exclude 'node_modules'  --exclude '.cache' 
#--delete

ssh root@188.120.244.199 <<'ENDSSH'
cd ~/f
./prod
ENDSSH
