#!/bin/bash

# set -x
set -o nounset
set -o errexit
set -o pipefail

if [ $# -eq 0 ]; then
  global=--experimental-repl-await
else
  global="$1"
fi

git rev-parse HEAD > HEAD


pm2_opts=--no-autorestart
wallet_port=26678
maxport=8002
xln_cluster_args="ts-node src/xln --wallet-url=http://localhost:$wallet_port --color --mmonkey=$maxport"

# Clean up, stop all demoapps and nodes
npx pm2 flush  || true
npx pm2 delete all || true

pkill -f XLN >/dev/null || true
//killall node 2>/dev/null || true

#rm -rf data*
#rm -rf isolate*

echo "Generating with maxport $maxport"



npx pm2 start $pm2_opts --name wallet yarn -- parcel serve wallet/index.html -p $wallet_port

xln_node_args="-p8433 --rebalance $global"
npx pm2 start $pm2_opts --name xln8433 npx -- $xln_cluster_args $xln_node_args

for i in $(seq 8001 $maxport); do
  xln_node_args="-p$i $global"
  #if (( i < 8014 )); then
    #mkdir data$i
    npx pm2 start $pm2_opts --name xln$i npx -- $xln_cluster_args $xln_node_args
  #else
  #  npx pm2 start $pm2_opts --name xln$i npx -- $xln_cluster_args $xln_node_args -s
  #fi
done

npx pm2 attach $(node -p "`pm2 id xln8433`[0]")  

