/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ConsoleInterface extends ethers.utils.Interface {
  functions: {
    "log(string,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "log",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "log", data: BytesLike): Result;

  events: {
    "LogAddress(string,address)": EventFragment;
    "LogBool(string,bool)": EventFragment;
    "LogBytes(string,bytes)": EventFragment;
    "LogBytes32(string,bytes32)": EventFragment;
    "LogInt(string,int256)": EventFragment;
    "LogString(string,string)": EventFragment;
    "LogUint(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogBool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogBytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogBytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogInt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogString"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogUint"): EventFragment;
}

export class Console extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ConsoleInterface;

  functions: {
    "log(string,bytes)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,address)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,bytes32)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,int256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,string)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,uint256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "log(string,bool)"(
      s: string,
      x: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "log(string,bytes)"(
    s: string,
    x: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,address)"(
    s: string,
    x: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,bytes32)"(
    s: string,
    x: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,int256)"(
    s: string,
    x: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,string)"(
    s: string,
    x: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,uint256)"(
    s: string,
    x: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "log(string,bool)"(
    s: string,
    x: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "log(string,bytes)"(
      s: string,
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address)"(
      s: string,
      x: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bytes32)"(
      s: string,
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,int256)"(
      s: string,
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,string)"(
      s: string,
      x: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256)"(
      s: string,
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool)"(
      s: string,
      x: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LogAddress(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, string], { arg0: string; arg1: string }>;

    LogBool(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, boolean], { arg0: string; arg1: boolean }>;

    LogBytes(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, string], { arg0: string; arg1: string }>;

    LogBytes32(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, string], { arg0: string; arg1: string }>;

    LogInt(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, BigNumber], { arg0: string; arg1: BigNumber }>;

    LogString(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, string], { arg0: string; arg1: string }>;

    LogUint(
      undefined: null,
      undefined: null
    ): TypedEventFilter<[string, BigNumber], { arg0: string; arg1: BigNumber }>;
  };

  estimateGas: {
    "log(string,bytes)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,address)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,bytes32)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,int256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,string)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,uint256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "log(string,bool)"(
      s: string,
      x: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "log(string,bytes)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,address)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,bytes32)"(
      s: string,
      x: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,int256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,string)"(
      s: string,
      x: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,uint256)"(
      s: string,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "log(string,bool)"(
      s: string,
      x: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
